apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type:
  selector:
    app:
  ports:
    - name: http
      port:
      targetPort:
      nodePort:
    - name: agent
      port:
      targetPort:
      nodePort:
